updating readme [skip ci]

diff --git a/.github/workflows/upload-model-to-dockerhub.yml b/.github/workflows/upload-model-to-dockerhub.yml
--- a/.github/workflows/upload-model-to-dockerhub.yml
+++ b/.github/workflows/upload-model-to-dockerhub.yml
@@ -36,6 +36,7 @@ jobs:
           fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
           lfs: 'true'
 
+# This might stop working in the future, so we need to keep an eye on it
       - name: Free Disk Space (Ubuntu)
         uses: jlumbroso/free-disk-space@main
         with:
@@ -102,15 +103,12 @@ jobs:
         run: |
           ersilia -v fetch ${{ github.event.repository.name }} --from_dockerhub
           ersilia -v serve ${{ github.event.repository.name }}
-          ersilia -v run -i "CCCC" -o "output.json"
-          expected=$(jq '.[0].output.outcome[]' output.json | wc -l)
-          result=$(jq '.[0].output.outcome[] | select(. != null)' output.json | wc -l)
-          echo "Expected correct outcomes $expected"
-          echo "Returned correct outcomes $result"
-          if ! ([ $result -gt 0 ] && [ $result -le $expected ])
-            then
-              echo "Error in model output, aborting build and push"
-              exit 1
+          ersilia -v run -i "CCCC" -o "output.csv"
+          ersilia close
+          output=$(python .github/scripts/verify_model_outcome.py output.csv)
+          if echo "$output" | grep -q "All outcomes are null"; then
+            echo "Error in model outcome, aborting build"
+            exit 1
           fi
         env:
           PULL_IMAGE: n
